           document.addEventListener("DOMContentLoaded", function() {
               // Array of daily texts
               const shaelynMbaso1 = [
//   "Day Zero",
   // January
"The best way to get started is to quit talking and begin doing. – Walt Disney, January 1",
"Don't be afraid to give up the good to go for the great. – John D. Rockefeller, January 2",
"The secret to financial success is to save and invest wisely. – Unknown, January 3",
"Wealth is the ability to fully experience life. – Henry David Thoreau, January 4",
"The best time to plant a tree was 20 years ago. The second-best time is now. – Chinese Proverb, January 5",
"Success is not about money. It’s about making a difference. – Unknown, January 6",
"Hard work beats talent when talent doesn't work hard. – Tim Notke, January 7",
"The greatest wealth is to live content with little. – Plato, January 8",
"The harder you work for something, the greater you’ll feel when you achieve it. – Unknown, January 9",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, January 10",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, January 11",
"Financial independence is a mindset, not a number. – Unknown, January 12",
"An investment in education always pays the best interest. – Benjamin Franklin, January 13",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, January 14",
"The best investment on earth is earth. – Louis Glickman, January 15",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, January 16",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, January 17",
"If you want to be rich, don’t wait. The time will never be just right. – Napoleon Hill, January 18",
"The more you save today, the more you will have for tomorrow. – Unknown, January 19",
"The only way to do great work is to love what you do. – Steve Jobs, January 20",
"In the middle of difficulty lies opportunity. – Albert Einstein, January 21",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, January 22",
"The greatest asset you can have is the ability to earn. – Unknown, January 23",
"Money is a terrible master but an excellent servant. – P.T. Barnum, January 24",
"Investing is the intersection of economics and psychology. – Seth Klarman, January 25",
"Entrepreneurship is not a science; it’s a practice. – Peter Drucker, January 26",
"Wealth is the product of a man’s capacity to think. – Ayn Rand, January 27",
"The key to wealth is to learn and apply. – Robert Kiyosaki, January 28",
"Your financial freedom is directly related to the amount of effort you put into your financial education. – Unknown, January 29",
"If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson, January 30",
"The best investment you can make is in your own skills. – Unknown, January 31",
               
               
               
               
   // February
"Opportunities are like sunrises. If you wait too long, you miss them. – William Arthur Ward, February 1",
"Never depend on a single income. Make investment to create a second source. – Warren Buffett, February 2",
"Don’t wait for the right opportunity: create it. – George Bernard Shaw, February 3",
"Success is a journey, not a destination. – Arthur Ashe, February 4",
"The most important investment you can make is in yourself. – Warren Buffett, February 5",
"Success is not just about making money. It’s about making a difference. – Unknown, February 6",
"The only limit to your impact is your imagination and commitment. – Tony Robbins, February 7",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, February 8",
"In the middle of difficulty lies opportunity. – Albert Einstein, February 9",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, February 10",
"The greatest asset you can have is the ability to earn. – Unknown, February 11",
"Money is a terrible master but an excellent servant. – P.T. Barnum, February 12",
"Investing is the intersection of economics and psychology. – Seth Klarman, February 13",
"Entrepreneurship is not a science; it’s a practice. – Peter Drucker, February 14",
"Wealth is the product of a man’s capacity to think. – Ayn Rand, February 15",
"The key to wealth is to learn and apply. – Robert Kiyosaki, February 16",
"Your financial freedom is directly related to the amount of effort you put into your financial education. – Unknown, February 17",
"If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson, February 18",
"The best investment you can make is in your own skills. – Unknown, February 19",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, February 20",
"Financial independence is a mindset, not a number. – Unknown, February 21",
"An investment in education always pays the best interest. – Benjamin Franklin, February 22",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, February 23",
"The best investment on earth is earth. – Louis Glickman, February 24",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, February 25",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, February 26",
"If you want to be rich, don’t wait. The time will never be just right. – Napoleon Hill, February 27",
//"The more you save today, the more you will have for tomorrow. – Unknown, February 28",
//"The only way to do great work is to love what you do. – Steve Jobs, February 29",
               
               
               
   // March
"The best way to predict the future is to create it. – Peter Drucker, March 1",
"Do not save what is left after spending, but spend what is left after saving. – Warren Buffett, March 2",
"An investment in knowledge pays the best interest. – Benjamin Franklin, March 3",
"The key to financial freedom and great wealth is a person’s ability to convert earned income into passive income and/or portfolio income. – Robert Kiyosaki, March 4",
"Banking is very good business if you don’t do anything foolish. – Warren Buffett, March 5",
"Entrepreneurship is neither a science nor an art. It is a practice. – Peter Drucker, March 6",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, March 7",
"The more you learn, the more you earn. – Warren Buffett, March 8",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, March 9",
"Opportunities don't happen. You create them. – Chris Grosser, March 10",
"The rich invest in time, the poor invest in money. – Warren Buffett, March 11",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, March 12",
"Entrepreneurs are willing to work 80 hours a week to avoid working 40 hours a week. – Lori Greiner, March 13",
"The stock market is filled with individuals who know the price of everything, but the value of nothing. – Philip Fisher, March 14",
"It does not matter how slowly you go as long as you do not stop. – Confucius, March 15",
"The secret to wealth is simple: Buy assets and avoid liabilities. – Robert Kiyosaki, March 16",
"Money is a terrible master but an excellent servant. – P.T. Barnum, March 17",
"To be successful, you must act big, think big, and talk big. – Aristotle Onassis, March 18",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, March 19",
"A goal without a plan is just a wish. – Antoine de Saint-Exupéry, March 20",
"Opportunities are usually disguised as hard work, so most people don’t recognize them. – Ann Landers, March 21",
"You can’t build a reputation on what you are going to do. – Henry Ford, March 22",
"The best investment you can make is in yourself. – Warren Buffett, March 23",
"Success is not in what you have, but who you are. – Bo Bennett, March 24",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, March 25",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, March 26",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, March 27",
"The harder I work, the luckier I get. – Samuel Goldwyn, March 28",
"It’s not about ideas. It’s about making ideas happen. – Scott Belsky, March 29",
"The best time to plant a tree was 20 years ago. The second best time is now. – Chinese Proverb, March 30",
"To be successful, you must first believe that you can be. – Nikos Kazantzakis, March 31",
               
               
   // April
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill, April 1",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, April 2",
"The greatest wealth is to live content with little. – Plato, April 3",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, April 4",
"If you want to be rich, don’t wait. The time will never be just right. – Napoleon Hill, April 5",
"Financial freedom is available to those who learn about it and work for it. – Robert Kiyosaki, April 6",
"The best investment on earth is earth. – Louis Glickman, April 7",
"An investment in education always pays the best interest. – Benjamin Franklin, April 8",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, April 9",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, April 10",
"Money often costs too much. – Ralph Waldo Emerson, April 11",
"The only way to do great work is to love what you do. – Steve Jobs, April 12",
"Opportunities are like sunrises. If you wait too long, you miss them. – William Arthur Ward, April 13",
"The more you save today, the more you will have for tomorrow. – Unknown, April 14",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, April 15",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, April 16",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, April 17",
"Hard work beats talent when talent doesn't work hard. – Tim Notke, April 18",
"Investing in yourself is the best investment you will ever make. – Robin Sharma, April 19",
"The best way to increase your net worth is to increase your self-worth. – Robin Sharma, April 20",
"If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson, April 21",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, April 22",
"The road to success is always under construction. – Lily Tomlin, April 23",
"The best way to predict the future is to create it. – Peter Drucker, April 24",
"To be successful, you must act big, think big, and talk big. – Aristotle Onassis, April 25",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, April 26",
"It is never too late to be what you might have been. – George Eliot, April 27",
"The harder you work for something, the greater you’ll feel when you achieve it. – Unknown, April 28",
"The secret to financial success is to save and invest wisely. – Unknown, April 29",
"Success is a journey, not a destination. – Arthur Ashe, April 30",
               
               
   // May
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, May 1",
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer, May 2",
"The best investment you can make is in your own skills. – Unknown, May 3",
"The harder I work, the luckier I get. – Samuel Goldwyn, May 4",
"Don’t watch the clock; do what it does. Keep going. – Sam Levenson, May 5",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, May 6",
"If you want to achieve greatness, stop asking for permission. – Anonymous, May 7",
"Money is a terrible master but an excellent servant. – P.T. Barnum, May 8",
"An investment in knowledge pays the best interest. – Benjamin Franklin, May 9",
"Entrepreneurship is neither a science nor an art. It is a practice. – Peter Drucker, May 10",
"Success is not in what you have, but who you are. – Bo Bennett, May 11",
"The stock market is designed to transfer money from the Active to the Patient. – Warren Buffett, May 12",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, May 13",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, May 14",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, May 15",
"If you want to be rich, don’t wait. The time will never be just right. – Napoleon Hill, May 16",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, May 17",
"The best way to predict the future is to create it. – Peter Drucker, May 18",
"Investing is the intersection of economics and psychology. – Seth Klarman, May 19",
"The more you learn, the more you earn. – Warren Buffett, May 20",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, May 21",
"Opportunities are like sunrises. If you wait too long, you miss them. – William Arthur Ward, May 22",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, May 23",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, May 24",
"It’s not about ideas. It’s about making ideas happen. – Scott Belsky, May 25",
"The best investment on earth is earth. – Louis Glickman, May 26",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, May 27",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, May 28",
"The best way to increase your net worth is to increase your self-worth. – Robin Sharma, May 29",
"Success is not about money. It’s about making a difference. – Unknown, May 30",
"The only way to do great work is to love what you do. – Steve Jobs, May 31",
               
               
   // June
"The journey of a thousand miles begins with one step. – Lao Tzu, June 1",
"Success is the sum of small efforts, repeated day in and day out. – Robert Collier, June 2",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, June 3",
"If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson, June 4",
"Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett, June 5",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, June 6",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, June 7",
"Opportunities don't happen. You create them. – Chris Grosser, June 8",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, June 9",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, June 10",
"Success is not in what you have, but who you are. – Bo Bennett, June 11",
"The best investment you can make is in your own skills. – Unknown, June 12",
"Money is a terrible master but an excellent servant. – P.T. Barnum, June 13",
"Entrepreneurship is neither a science nor an art. It is a practice. – Peter Drucker, June 14",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, June 15",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, June 16",
"The secret to financial success is to save and invest wisely. – Unknown, June 17",
"The more you learn, the more you earn. – Warren Buffett, June 18",
"The best way to predict the future is to create it. – Peter Drucker, June 19",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, June 20",
"Don’t wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats, June 21",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, June 22",
"The more you save today, the more you will have for tomorrow. – Unknown, June 23",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, June 24",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, June 25",
"Success is not just about making money. It’s about making a difference. – Unknown, June 26",
"It’s not about ideas. It’s about making ideas happen. – Scott Belsky, June 27",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, June 28",
"If you want to be rich, don’t wait. The time will never be just right. – Napoleon Hill, June 29",
"The greatest wealth is to live content with little. – Plato, June 30",
               
               
   // July
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer, July 1",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, July 2",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, July 3",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, July 4",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, July 5",
"The best investment on earth is earth. – Louis Glickman, July 6",
"The more you learn, the more you earn. – Warren Buffett, July 7",
"Your income is directly related to your philosophy, not the economy. – Jim Rohn, July 8",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, July 9",
"An investment in knowledge pays the best interest. – Benjamin Franklin, July 10",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, July 11",
"The only way to do great work is to love what you do. – Steve Jobs, July 12",
"Opportunities are like sunrises. If you wait too long, you miss them. – William Arthur Ward, July 13",
"The more you save today, the more you will have for tomorrow. – Unknown, July 14",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, July 15",
"The best way to predict the future is to create it. – Peter Drucker, July 16",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, July 17",
"Success is not in what you have, but who you are. – Bo Bennett, July 18",
"The key to wealth is to learn and apply. – Robert Kiyosaki, July 19",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, July 20",
"The harder I work, the luckier I get. – Samuel Goldwyn, July 21",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, July 22",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, July 23",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, July 24",
"Don’t wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats, July 25",
"The best investment you can make is in your own skills. – Unknown, July 26",
"If you want something you’ve never had, you must be willing to do something you’ve never done. – Thomas Jefferson, July 27",
"Success is not just about making money. It’s about making a difference. – Unknown, July 28",
"The more you save today, the more you will have for tomorrow. – Unknown, July 29",
"The road to success is always under construction. – Lily Tomlin, July 30",
"The secret to financial success is to save and invest wisely. – Unknown, July 31",
               
               
   // August
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill, August 1",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, August 2",
"An investment in knowledge pays the best interest. – Benjamin Franklin, August 3",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, August 4",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, August 5",
"The road to success is always under construction. – Lily Tomlin, August 6",
"The greatest wealth is to live content with little. – Plato, August 7",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, August 8",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, August 9",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, August 10",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, August 11",
"The more you learn, the more you earn. – Warren Buffett, August 12",
"Money is a terrible master but an excellent servant. – P.T. Barnum, August 13",
"The secret to financial success is to save and invest wisely. – Unknown, August 14",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, August 15",
"Opportunities don’t happen. You create them. – Chris Grosser, August 16",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, August 17",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, August 18",
"The best investment on earth is earth. – Louis Glickman, August 19",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, August 20",
"The best way to predict the future is to create it. – Peter Drucker, August 21",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, August 22",
"The only way to do great work is to love what you do. – Steve Jobs, August 23",
"Success is not in what you have, but who you are. – Bo Bennett, August 24",
"Don’t wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats, August 25",
"If you want to achieve greatness, stop asking for permission. – Anonymous, August 26",
"The harder I work, the luckier I get. – Samuel Goldwyn, August 27",
"You don’t have to be great to start, but you have to start to be great. – Zig Ziglar, August 28",
"The best investment you can make is in your own skills. – Unknown, August 29",
"Success is not about money. It’s about making a difference. – Unknown, August 30",
"The more you save today, the more you will have for tomorrow. – Unknown, August 31",
               
               
   // September
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, September 1",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, September 2",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, September 3",
"Opportunities don’t happen. You create them. – Chris Grosser, September 4",
"The best investment you can make is in your own skills. – Unknown, September 5",
"The best way to predict the future is to create it. – Peter Drucker, September 6",
"The more you learn, the more you earn. – Warren Buffett, September 7",
"The harder I work, the luckier I get. – Samuel Goldwyn, September 8",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, September 9",
"Success is not in what you have, but who you are. – Bo Bennett, September 10",
"The greatest wealth is to live content with little. – Plato, September 11",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, September 12",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, September 13",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, September 14",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, September 15",
"Money is a terrible master but an excellent servant. – P.T. Barnum, September 16",
"The road to success is always under construction. – Lily Tomlin, September 17",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, September 18",
"The only way to do great work is to love what you do. – Steve Jobs, September 19",
"The secret to financial success is to save and invest wisely. – Unknown, September 20",
"If you want to achieve greatness, stop asking for permission. – Anonymous, September 21",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, September 22",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, September 23",
"The more you save today, the more you will have for tomorrow. – Unknown, September 24",
"Success is not just about making money. It’s about making a difference. – Unknown, September 25",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, September 26",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, September 27",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, September 28",
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer, September 29",
"Opportunities are like sunrises. If you wait too long, you miss them. – William Arthur Ward, September 30",
               
               
   // October
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, October 1",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, October 2",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, October 3",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, October 4",
"The only way to do great work is to love what you do. – Steve Jobs, October 5",
"Opportunities don’t happen. You create them. – Chris Grosser, October 6",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, October 7",
"The more you learn, the more you earn. – Warren Buffett, October 8",
"The best investment you can make is in your own skills. – Unknown, October 9",
"Success is not in what you have, but who you are. – Bo Bennett, October 10",
"The greatest wealth is to live content with little. – Plato, October 11",
"Money is a terrible master but an excellent servant. – P.T. Barnum, October 12",
"The road to success is always under construction. – Lily Tomlin, October 13",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, October 14",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, October 15",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, October 16",
"The best way to predict the future is to create it. – Peter Drucker, October 17",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, October 18",
"The more you save today, the more you will have for tomorrow. – Unknown, October 19",
"Success is not just about making money. It’s about making a difference. – Unknown, October 20",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, October 21",
"The secret to financial success is to save and invest wisely. – Unknown, October 22",
"The harder I work, the luckier I get. – Samuel Goldwyn, October 23",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, October 24",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, October 25",
"If you want to achieve greatness, stop asking for permission. – Anonymous, October 26",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, October 27",
"The best investment on earth is earth. – Louis Glickman, October 28",
"The more you learn, the more you earn. – Warren Buffett, October 29",
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer, October 30",
"The best way to predict the future is to create it. – Peter Drucker, October 31",
               
               
   // November
"Success is not the key to happiness. Happiness is the key to success. – Albert Schweitzer, November 1",
"Opportunities don’t happen. You create them. – Chris Grosser, November 2",
"The only way to do great work is to love what you do. – Steve Jobs, November 3",
"The best investment you can make is in your own skills. – Unknown, November 4",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, November 5",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, November 6",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, November 7",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, November 8",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, November 9",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, November 10",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, November 11",
"Money is a terrible master but an excellent servant. – P.T. Barnum, November 12",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, November 13",
"The road to success is always under construction. – Lily Tomlin, November 14",
"The greatest wealth is to live content with little. – Plato, November 15",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, November 16",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, November 17",
"The best way to predict the future is to create it. – Peter Drucker, November 18",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, November 19",
"The more you learn, the more you earn. – Warren Buffett, November 20",
"Success is not in what you have, but who you are. – Bo Bennett, November 21",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, November 22",
"The secret to financial success is to save and invest wisely. – Unknown, November 23",
"If you want to achieve greatness, stop asking for permission. – Anonymous, November 24",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, November 25",
"The more you save today, the more you will have for tomorrow. – Unknown, November 26",
"The harder I work, the luckier I get. – Samuel Goldwyn, November 27",
"Success is not just about making money. It’s about making a difference. – Unknown, November 28",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, November 29",
"The best investment on earth is earth. – Louis Glickman, November 30",
               
               
   // December
"Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill, December 1",
"Opportunities don’t happen. You create them. – Chris Grosser, December 2",
"The only way to do great work is to love what you do. – Steve Jobs, December 3",
"The best investment you can make is in your own skills. – Unknown, December 4",
"Dream big, work hard, stay focused, and surround yourself with good people. – Unknown, December 5",
"The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt, December 6",
"The more you learn, the more you earn. – Warren Buffett, December 7",
"The road to success is always under construction. – Lily Tomlin, December 8",
"Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill, December 9",
"The best way to predict the future is to create it. – Peter Drucker, December 10",
"Hard work beats talent when talent doesn’t work hard. – Tim Notke, December 11",
"Money is a terrible master but an excellent servant. – P.T. Barnum, December 12",
"The greatest wealth is to live content with little. – Plato, December 13",
"Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau, December 14",
"You miss 100% of the shots you don’t take. – Wayne Gretzky, December 15",
"The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt, December 16",
"The best way to find yourself is to lose yourself in the service of others. – Mahatma Gandhi, December 17",
"Don’t be afraid to give up the good to go for the great. – John D. Rockefeller, December 18",
"The more you save today, the more you will have for tomorrow. – Unknown, December 19",
"Success is not in what you have, but who you are. – Bo Bennett, December 20",
"Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe, December 21",
"The secret to financial success is to save and invest wisely. – Unknown, December 22",
"If you want to achieve greatness, stop asking for permission. – Anonymous, December 23",
"The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will. – Vince Lombardi, December 24",
"The only place where success comes before work is in the dictionary. – Vidal Sassoon, December 25",
"The stock market is a device for transferring money from the impatient to the patient. – Warren Buffett, December 26",
"Success is not just about making money. It’s about making a difference. – Unknown, December 27",
"The more you learn, the more you earn. – Warren Buffett, December 28",
"The way to wealth is to learn something new every day. – Robert Kiyosaki, December 29",
"The harder I work, the luckier I get. – Samuel Goldwyn, December 30",
"The best investment on earth is earth. – Louis Glickman, December 31"
               
               
   // Add more texts for each day
               ];
   
               // Get today's date
               const today = new Date();
               const dayOfYear = today.getDate() + today.getMonth() * 30;
   
               // Choose the daily text based on the day of the year
               const selectedText = shaelynMbaso1[dayOfYear % shaelynMbaso1.length];
   
               // Display the daily text on the webpage
               const dailyTextElement = document.getElementById("shaelynMbaso1");
               dailyTextElement.textContent = selectedText;
   
               // Display the current date
               const currentDateElement = document.getElementById("currentDate");
               const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
               currentDateElement.textContent = today.toLocaleDateString('en-US', options);
           });
